#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#pre-commit

import common

import forbidtoken
import filesize
import codingstyle
#import check_xml
#import cppcheck

DEFAULT_HOOKS = [
        'crlf',
        'tab',
        'filesize',
        'oslm_log',
        'digraphs',
        'codingstyle',
        'doxygen',
        'copain',
        'check_xml',
        'cppcheck'
        ]

hooks = {}
hooks.update(forbidtoken.hooks)
hooks.update(filesize.hooks)
hooks.update(codingstyle.hooks)
#hooks.update(check_xml.hooks)
#hooks.update(cppcheck.hooks)

active_hooks = common.get_option('fw4spl-hooks.hooks', default=DEFAULT_HOOKS).split()
common.note ('Enabled hooks: ' + ', '.join(active_hooks))

files = [f for f in common.files_staged_for_commit()]

if files:
    result = [f(files) for name,f in hooks.items() if name in active_hooks]
    result = any(result)

    exit(result)

exit(0)

